### PR TITLE
feat: upgrade to 1.x format

### PR DESCRIPTION
**Pull request by jlengstorf**
- `context` -> `namespace`
- `model`/`connector` -> `context`
- Simplified resolvers into a standard GraphQL resolvers object
- Split mocks into a separate property
- Simplified tests
- Updated packages

### CODE REVIEW

**Comment by jlengstorf** [comment]
@ecwyne I think we're just about ready to pull the trigger on 1.x. If you've got a little time to poke at this in the next few days, we might be able to hit a stable 1.0.0 release this week. 🎉

**Comment by jlengstorf** [comment]
@ecwyne pinging on this for a review when you have a chance.

**Comment by ecwyne** [comment]
Also 👍 on `degit`. I've never seen that tool, but it looks incredibly useful

**Comment by jlengstorf** [comment]
Seriously. I saw it on @Rich-Harris's feed and immediately changed how I think about writing docs.

**Pull request merged**
